#!/usr/bin/env python3
"""Render the checked evidence-map CSV as a compact LaTeX longtable."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "_pdfs" / "manifests" / "all_204_note_entries.csv"
OUTPUT = ROOT / "appendix" / "evidence_map.tex"


def tex(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "π": r"$\pi$",
    }
    return "".join(replacements.get(char, char) for char in value)


def main() -> None:
    with INPUT.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if len(rows) != 204:
        raise SystemExit(f"expected 204 evidence records, found {len(rows)}")

    lines = [
        "% Generated by scripts/render_evidence_map.py; edit the source CSV, not this file.",
        r"\onecolumn",
        r"\section{Complete Evidence Map}",
        r"\label{app:evidence-map}",
        r"\small",
        r"Table~\ref{tab:evidence-map} lists every record in the evidence map. D denotes deep reading, M method-level reading, and A abstract-index horizon scanning. The machine-readable CSV is the authoritative companion artifact.",
        r"\setlength{\LTleft}{0pt}",
        r"\setlength{\LTright}{0pt}",
        r"\refstepcounter{table}\label{tab:evidence-map}",
        r"\begin{center}\textbf{Table~\thetable: Complete 204-work evidence map.}\end{center}",
        r"\begin{longtable}{@{}p{1.3cm}p{11.8cm}p{2.2cm}p{1.2cm}@{}}",
        r"\toprule",
        r"ID & Work & Year & Depth \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{4}{l}{\small\itshape Table~\ref{tab:evidence-map} continued}\\",
        r"\toprule",
        r"ID & Work & Year & Depth \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{4}{r}{\small Continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for row in rows:
        lines.append(
            f"{tex(row['note_id'])} & {tex(row['title'])} & {tex(row['year'])} & {tex(row['depth'])} \\\\"
        )
    lines.extend([r"\end{longtable}", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"rendered {len(rows)} records to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
