#!/usr/bin/env python3
"""Render the checked evidence-map CSV as a compact LaTeX longtable."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "_pdfs" / "manifests" / "evidence_map.csv"
OUTPUT = ROOT / "appendix" / "evidence_map.tex"


def tex(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "π": r"$\pi$",
    }
    return "".join(replacements.get(char, char) for char in value)


def main() -> None:
    with INPUT.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    expected_ids = [f"P{index:03d}" for index in range(1, len(rows) + 1)]
    actual_ids = [row["note_id"] for row in rows]
    if actual_ids != expected_ids:
        raise SystemExit("evidence-map IDs must be contiguous, ordered, and unique")
    deep = sum(row["depth"] == "D" for row in rows)
    method = sum(row["depth"] == "M" for row in rows)
    abstract = sum(row["depth"] == "A" for row in rows)

    lines = [
        "% Generated by scripts/render_evidence_map.py; edit the source CSV, not this file.",
        r"\onecolumn",
        r"\section{Complete Evidence Map}",
        r"\label{app:evidence-map}",
        r"\small",
        r"Table~\ref{tab:evidence-map} lists every record in the evidence map. D denotes deep reading, M method-level reading, and A an abstract-index record used only to track emerging work. The machine-readable CSV is the authoritative companion artifact.",
        r"\setlength{\LTleft}{0pt}",
        r"\setlength{\LTright}{0pt}",
        r"\refstepcounter{table}\label{tab:evidence-map}",
        rf"\begin{{center}}\textbf{{Table~\thetable: Complete {len(rows)}-work evidence map ({deep} D, {method} M, {abstract} A).}}\end{{center}}",
        r"\begin{longtable}{@{}p{1.3cm}p{11.8cm}p{2.2cm}p{1.2cm}@{}}",
        r"\toprule",
        r"ID & Work & Year & Depth \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{4}{l}{\small\itshape Table~\ref{tab:evidence-map} continued}\\",
        r"\toprule",
        r"ID & Work & Year & Depth \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{4}{r}{\small Continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for row in rows:
        lines.append(
            f"{tex(row['note_id'])} & {tex(row['title'])} & {tex(row['year'])} & {tex(row['depth'])} \\\\"
        )
    lines.extend([r"\end{longtable}", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"rendered {len(rows)} records to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
